#!/bin/sh

# This is the script that will be triggered upon a `git push` to the blue repo.
# The script stops the currently running application on the blue container and deploys the latest version of the application.

GIT_WORK_TREE=/home/ashwin_oke/deploy/blue-www/ git checkout -f

sudo docker pull localhost:5000/ncsu:latest  
sudo docker stop app_blue 
sudo docker rm app_blue
sudo docker rmi localhost:5000/ncsu:current_blue  
sudo docker tag localhost:5000/ncsu:latest localhost:5000/ncsu:current_blue
sudo docker run -p 50100:8080 -d --name app_blue localhost:5000/ncsu:current_blue
