redis_ambassador:
    container_name: "h2-redis-ambassador"
    image: svendowideit/ambassador
    expose:
        - "6379"
    environment:
        - REDIS_PORT_6379_TCP=tcp://192.168.33.10:6379

redis_client:
    container_name: "redis-client"
    image: relateiq/redis-cli
    links:
        - redis_ambassador:redis
